Added remaining steps

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -102,3 +102,173 @@ jobs:
         echo "Queue Name: ${{ steps.deploy.outputs.queueName }}"
         echo "Queue Storage Account: ${{ steps.deploy.outputs.queueStorageAccountName }}"
         echo "Storage Account Connection String: ${{ steps.deploy.outputs.storageAccountConnectionString }}"
+
+  testStorageQueue:
+    name: Test Storage Queue
+    needs:  [provision]
+    runs-on: ubuntu-latest
+    outputs:
+      startDate: ${{ steps.date.outputs.date }}
+    strategy:
+      fail-fast: false
+      matrix:
+        container: [1] #, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
+    steps:
+    - name: Get current date
+      id: date
+      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
+
+    - name: Put message 1
+      shell: bash
+      run: |
+        az storage message put \
+          --content "Hello Queue Reader App ${{ matrix.container }}-1" \
+          --queue-name "${{ needs.provision.outputs.queueName }}" \
+          --connection-string "${{ needs.provision.outputs.queueConnectionString }}"
+          
+    - name: Put message 2
+      shell: bash
+      run: |
+        az storage message put \
+          --content "Hello Queue Reader App ${{ matrix.container }}-2" \
+          --queue-name "${{ needs.provision.outputs.queueName }}" \
+          --connection-string "${{ needs.provision.outputs.queueConnectionString }}"
+          
+    - name: Put message 3
+      shell: bash
+      run: |
+        az storage message put \
+          --content "Hello Queue Reader App ${{ matrix.container }}-3" \
+          --queue-name "${{ needs.provision.outputs.queueName }}" \
+          --connection-string "${{ needs.provision.outputs.queueConnectionString }}"
+          
+    - name: Put message 4
+      shell: bash
+      run: |
+        az storage message put \
+          --content "Hello Queue Reader App ${{ matrix.container }}-4" \
+          --queue-name "${{ needs.provision.outputs.queueName }}" \
+          --connection-string "${{ needs.provision.outputs.queueConnectionString }}"
+          
+    - name: Put message 5
+      shell: bash
+      run: |
+        az storage message put \
+          --content "Hello Queue Reader App ${{ matrix.container }}-5" \
+          --queue-name "${{ needs.provision.outputs.queueName }}" \
+          --connection-string "${{ needs.provision.outputs.queueConnectionString }}"
+
+  validateStorageQueue:
+    name: Validate Storage Queue
+    needs: [testStorageQueue]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+    - name: Check Metrics
+      run: |
+        az config set extension.use_dynamic_install=yes_without_prompt
+        az provider register --namespace Microsoft.App
+        az provider register --namespace Microsoft.OperationalInsights
+
+        NAME=$PREFIX"acae"
+        LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az containerapp env show --name $NAME --resource-group $RESOURCEGROUP --query properties.appLogsConfiguration.logAnalyticsConfiguration.customerId --out tsv`
+
+        RESULT=`az monitor log-analytics query \
+          --workspace $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
+          --analytics-query "ContainerAppConsoleLogs_CL | where ContainerAppName_s == 'storagequeuereader' and Log_s contains 'Message ID' and TimeGenerated > todatetime('${{ needs.testStorageQueue.outputs.startDate }}') | summarize count()" \
+          --out tsv`
+        # Compare the number after the text PrimaryResult
+        MESSAGES=${RESULT:14:3}
+        if [ "$MESSAGES" -ge 100 ]; then
+          echo "Messages Processed: $MESSAGES, Success"
+        else
+          echo "Messages Processed: $MESSAGES, FAILED!"
+          exit 1
+        fi
+
+  testServiceBusQueue:
+    name: Test Service Bus Queue
+    needs:  [provision]
+    runs-on: ubuntu-latest
+    outputs:
+      startDate: ${{ steps.date.outputs.date }}
+    steps:
+    - name: Get current date
+      id: date
+      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
+
+    - uses: actions/checkout@master
+
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+    - uses: azure/arm-deploy@v1
+      name: Deploy Service Bus Queue Producer
+      id: deploy
+      with:
+        subscriptionId: ${{ env.SUBSCRIPTIONID }}
+        resourceGroupName: ${{ env.RESOURCEGROUP }}
+        template: ./src/Environment/service_bus_queue_producer.json
+        parameters: registryName="${{ needs.build.outputs.registryName }}" serviceBusName="${{ needs.provision.outputs.serviceBusName }}"
+        deploymentName: ${{ env.PREFIX }}sbp-${{ steps.date.outputs.date }}
+
+  validateServiceBusQueue:
+    name: Validate Service Bus Queue
+    needs: [testServiceBusQueue]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+    - name: Check Metrics
+      run: |
+        az config set extension.use_dynamic_install=yes_without_prompt
+        az provider register --namespace Microsoft.App
+        az provider register --namespace Microsoft.OperationalInsights
+
+        NAME=$PREFIX"acae"
+        LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az containerapp env show --name $NAME --resource-group $RESOURCEGROUP --query properties.appLogsConfiguration.logAnalyticsConfiguration.customerId --out tsv`
+
+        RESULT=`az monitor log-analytics query \
+          --workspace $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
+          --analytics-query "ContainerAppConsoleLogs_CL | where ContainerAppName_s == 'servicebusqueuereader' and Log_s contains 'Message ID' and TimeGenerated > todatetime('${{ needs.testStorageQueue.outputs.startDate }}') | summarize count()" \
+          --out tsv`
+        # Compare the number after the text PrimaryResult
+        MESSAGES=${RESULT:14:3}
+        if [ "$MESSAGES" -ge 100 ]; then
+          echo "Messages Processed: $MESSAGES, Success"
+        else
+          echo "Messages Processed: $MESSAGES, FAILED!"
+          exit 1
+        fi
+
+  cleanup:
+    name: Clean Up
+    needs: [validateStorageQueue,validateServiceBusQueue]
+    runs-on: ubuntu-latest
+    environment: 'cleanup'
+    steps:
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+    - name: Delete Log Analytics Workspace
+      continue-on-error: true
+      run: |
+        az monitor log-analytics workspace delete -g ${{ env.RESOURCEGROUP }} \
+          --workspace-name ${{ env.LOGANALYTICSWORKSPACENAME }} \
+          --force true --yes
+
+    - name: Delete Resource Group
+      continue-on-error: true
+      run: |
+        az group delete -g ${{ env.RESOURCEGROUP }} --yes
